server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: file://Users/user/dev-private/config-example2
#          uri: https://github.com/forest000014/config-example2.git
          search-paths: config1
#          search-paths: config1, config2
#          ignoreLocalSshSettings: true
#          privateKey: |
