spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/forest000014/config-example2.git
          search-paths: config1, config2
          ignoreLocalSshSettings: true
          privateKey: |
